export const ERROR_CORRECTION_EXERCISES = [
  { sentence: 'Mi hermano es muy cansado hoy.', errorWord: 'es', correction: 'está', explanation: 'Temporary states like tiredness use "estar", not "ser".' },
  { sentence: 'Yo soy en Madrid ahora mismo.', errorWord: 'soy', correction: 'estoy', explanation: '"Estar" is used for location, not "ser".' },
  { sentence: 'El libro es sobre la mesa.', errorWord: 'es', correction: 'está', explanation: 'Physical location uses "estar".' },
  { sentence: 'Tengo veinte años viejos.', errorWord: 'viejos', correction: 'años', explanation: 'In Spanish "tener X años" — you don\'t add "viejos".' },
  { sentence: 'Me gusta el fútbol mucho.', errorWord: 'mucho', correction: 'Me gusta mucho el fútbol', explanation: '"Mucho" goes after the verb: me gusta mucho.' },
  { sentence: 'Voy a la escuela en pie.', errorWord: 'en pie', correction: 'a pie', explanation: '"A pie" (on foot) is the correct expression.' },
  { sentence: 'Ella tiene caliente.', errorWord: 'tiene caliente', correction: 'tiene calor', explanation: '"Tener calor" means to be hot. "Caliente" is an adjective (the thing is hot).' },
  { sentence: 'Nosotros somos cansados.', errorWord: 'somos', correction: 'estamos', explanation: 'Tiredness is a temporary state → "estar" not "ser".' },
  { sentence: 'Vivo con mis padres desde cinco años.', errorWord: 'desde cinco años', correction: 'desde hace cinco años', explanation: '"Desde hace + time" expresses duration of an ongoing action.' },
  { sentence: 'Me gustan mucho la música.', errorWord: 'gustan', correction: 'gusta', explanation: '"La música" is singular, so use "gusta" not "gustan".' },
  { sentence: 'Ayer yo trabajé mucho en casa mía.', errorWord: 'casa mía', correction: 'mi casa', explanation: 'Possessives go before the noun: "mi casa" not "casa mía".' },
  { sentence: 'Tengo ganas de ir de vacaciones.', errorWord: '', correction: '', explanation: 'This sentence is actually correct! "Tener ganas de + infinitivo." '},
  { sentence: 'Fui al cine con mis amigos ayer en la noche.', errorWord: 'en la noche', correction: 'por la noche', explanation: 'Time of day: "por la noche", not "en la noche".' },
  { sentence: 'El agua está muy caliente — está buena.', errorWord: '', correction: '', explanation: 'Correct! "Estar buena" means it tastes good.' },
  { sentence: 'Habla usted muy bien el español, ¿no es verdad?', errorWord: '', correction: '', explanation: 'Correct formal expression.' },
  { sentence: 'Me llamo María y tengo veinticinco años viejos.', errorWord: 'años viejos', correction: 'veinticinco años', explanation: 'Never add "viejos" after age in Spanish.' },
  { sentence: 'Ella es muy inteligente y habla bien.', errorWord: '', correction: '', explanation: 'Correct! "Ser" for a permanent characteristic like intelligence.' },
  { sentence: 'Hoy hace muy calor en la calle.', errorWord: 'muy calor', correction: 'mucho calor', explanation: '"Calor" is a noun, so use "mucho" not "muy". "Hace mucho calor."' },
  { sentence: 'Necesito aprender para hablar mejor el español.', errorWord: 'para hablar mejor el español', correction: 'para hablar mejor español', explanation: 'After "hablar" with a language, the article is usually omitted.' },
  { sentence: 'Ayer estuve con mí amigo en el parque.', errorWord: 'mí', correction: 'mi', explanation: '"Mi" (without accent) is the possessive. "Mí" (with accent) is the pronoun after prepositions.' },
  { sentence: 'El clase de español es muy interesante.', errorWord: 'El', correction: 'La', explanation: '"Clase" is feminine → "la clase".' },
  { sentence: 'Quiero ir de vacaciones a la España.', errorWord: 'la España', correction: 'España', explanation: 'Country names in Spanish generally don\'t use an article: "ir a España".' },
  { sentence: 'Ayer comiste en un restaurante bueno.', errorWord: '', correction: '', explanation: 'Correct! Preterite tú form: comiste.' },
  { sentence: 'Yo estoy muy contento de conocerte.', errorWord: '', correction: '', explanation: 'Correct! "Estar contento" is correct for an emotional state.' },
  { sentence: 'Me gusta los domingos quedar con amigos.', errorWord: 'Me gusta los domingos', correction: 'Los domingos me gusta', explanation: 'Time expressions usually go at the beginning or end: "Los domingos me gusta quedar con amigos."' },
  { sentence: 'Fui a compras ayer por la tarde.', errorWord: 'a compras', correction: 'de compras', explanation: '"Ir de compras" = to go shopping.' },
  { sentence: 'Estoy de acuerdo contigo totalmente.', errorWord: '', correction: '', explanation: 'Correct! "Estar de acuerdo con" = to agree with.' },
  { sentence: 'Ella tiene mucho fría hoy.', errorWord: 'mucho fría', correction: 'mucho frío', explanation: '"Frío" is a noun here (tener frío). No adjective agreement needed.' },
  { sentence: 'A mí me gusto el chocolate negro.', errorWord: 'gusto', correction: 'gusta', explanation: '"El chocolate" is singular → "gusta" not "gusto". Yo no soy el sujeto aquí.' },
  { sentence: 'El fin de semana pasado fui a la playa con mí familia.', errorWord: 'mí', correction: 'mi', explanation: 'Possessive "mi" has no accent mark.' },
]