// Grammar reference cards for A1/A2 Spanish learners

export const GRAMMAR_CARDS = [
  {
    id: 'gc-01',
    level: 'A1',
    category: 'ser / estar',
    title: 'SER vs ESTAR — základy',
    rule: 'SER = stále / identita\nESTAR = dočasné / poloha / stav',
    examples: [
      { es: 'Soy estudiante.', sk: 'Som študentka.', note: 'identita → ser' },
      { es: 'Estoy cansada.', sk: 'Som unavená.', note: 'dočasný stav → estar' },
      { es: 'Madrid está en España.', sk: 'Madrid je v Španielsku.', note: 'poloha → estar' },
      { es: 'El café es malo.', sk: 'Káva je zlá.', note: 'trvalá vlastnosť → ser' },
    ],
    tip: 'Ak si vieš predstaviť, že sa to čoskoro zmení, použi ESTAR.',
  },
  {
    id: 'gc-02',
    level: 'A1',
    category: 'tener',
    title: 'Výrazy s TENER',
    rule: 'Mnohé pocity sa v španielčine vyjadrujú TENER + podstatné meno\n(nie SER/ESTAR + prídavné meno ako v slovenčine)',
    examples: [
      { es: 'Tengo hambre.', sk: 'Mám hlad.', note: 'hlad' },
      { es: 'Tengo sed.', sk: 'Mám smäd.', note: 'smäd' },
      { es: 'Tengo frío / calor.', sk: 'Je mi zima / teplo.', note: 'teplo/zima' },
      { es: 'Tengo miedo.', sk: 'Mám strach.', note: 'strach' },
      { es: 'Tengo sueño.', sk: 'Som ospalá.', note: 'ospalosť' },
    ],
    tip: 'Nikdy nehovor "Estoy hambre" — vždy "Tengo hambre".',
  },
  {
    id: 'gc-03',
    level: 'A1',
    category: 'gustar',
    title: 'GUSTAR — páčiť sa',
    rule: 'Podmet a sloveso sú prehodené:\nVec, ktorá sa páči, je podmet → sloveso sa s ním zhoduje',
    examples: [
      { es: 'Me gusta el café.', sk: 'Páči sa mi káva.', note: 'jednotné číslo → gusta' },
      { es: 'Me gustan los gatos.', sk: 'Páčia sa mi mačky.', note: 'množné číslo → gustan' },
      { es: 'Te gusta bailar.', sk: 'Páči sa ti tancovať.', note: 'infinitív → gusta' },
      { es: 'Le gusta mucho.', sk: 'Veľmi sa mu páči.', note: 'él/ella/usted' },
    ],
    tip: 'Pýtaj sa: čo sa páči? Ak je to množné číslo → gustan. Ak jednotné číslo/infinitív → gusta.',
  },
  {
    id: 'gc-04',
    level: 'A1',
    category: 'artículos',
    title: 'Členy — el / la / los / las / un / una',
    rule: 'Každé podstatné meno má rod (mužský/ženský).\nel/un = mužský rod, jednotné číslo\nla/una = ženský rod, jednotné číslo\nlos/unos = mužský rod, množné číslo\nlas/unas = ženský rod, množné číslo',
    examples: [
      { es: 'el libro / un libro', sk: 'kniha (m.)', note: 'väčšina slov na -o = mužský rod' },
      { es: 'la casa / una casa', sk: 'dom (f.)', note: 'väčšina slov na -a = ženský rod' },
      { es: 'el día / el mapa', sk: 'výnimky — mužský rod', note: 'výnimky' },
      { es: 'la clase / la noche', sk: 'výnimky — ženský rod', note: 'výnimky končiace na -e' },
    ],
    tip: 'Uč sa člen spolu s každým novým slovom: "el trabajo", nie len "trabajo".',
  },
  {
    id: 'gc-05',
    level: 'A1',
    category: 'presente',
    title: 'Prítomný čas — pravidelné slovesá',
    rule: '-AR slovesá: -o, -as, -a, -amos, -áis, -an\n-ER slovesá: -o, -es, -e, -emos, -éis, -en\n-IR slovesá: -o, -es, -e, -imos, -ís, -en',
    examples: [
      { es: 'Hablo / hablas / habla', sk: 'hovorím / hovoríš / hovorí', note: 'hablar (-AR)' },
      { es: 'Como / comes / come', sk: 'jem / ješ / je', note: 'comer (-ER)' },
      { es: 'Vivo / vives / vive', sk: 'bývam / bývaš / býva', note: 'vivir (-IR)' },
    ],
    tip: 'Tvar yo vždy končí na -o pri pravidelných slovesách.',
  },
  {
    id: 'gc-06',
    level: 'A1',
    category: 'negación',
    title: 'Zápor — NO',
    rule: 'Daj NO priamo pred sloveso.\nDvojitý zápor je v španielčine správny!',
    examples: [
      { es: 'No hablo inglés.', sk: 'Nehovorím po anglicky.', note: 'jednoduchý zápor' },
      { es: 'No tengo nada.', sk: 'Nemám nič.', note: 'no + nada = dvojitý zápor ✓' },
      { es: 'No voy nunca.', sk: 'Nikdy nechodím.', note: 'no + nunca ✓' },
      { es: 'No hay nadie aquí.', sk: 'Tu nie je nikto.', note: 'no + nadie ✓' },
    ],
    tip: 'Dvojitý zápor je v španielčine POVINNÝ — "No tengo nada" je správne.',
  },
  {
    id: 'gc-07',
    level: 'A1',
    category: 'preposiciones',
    title: 'Kľúčové predložky: A, EN, DE',
    rule: 'A = do / na (smer, čas)\nEN = v / na (poloha, dopravný prostriedok)\nDE = z / od (pôvod, vlastníctvo)',
    examples: [
      { es: 'Voy a Madrid.', sk: 'Idem do Madridu.', note: 'a = smer' },
      { es: 'Vivo en España.', sk: 'Bývam v Španielsku.', note: 'en = poloha' },
      { es: 'Soy de Eslovaquia.', sk: 'Som zo Slovenska.', note: 'de = pôvod' },
      { es: 'Voy en metro.', sk: 'Idem metrom.', note: 'en = doprava' },
    ],
    tip: '"A pie" (pešo) a "en coche" (autom) — nauč sa tieto ako ustálené frázy.',
  },
  {
    id: 'gc-08',
    level: 'A2',
    category: 'pretérito indefinido',
    title: 'Minulý čas (pretérito indefinido) — pravidelné',
    rule: '-AR: -é, -aste, -ó, -amos, -asteis, -aron\n-ER/-IR: -í, -iste, -ió, -imos, -isteis, -ieron',
    examples: [
      { es: 'Ayer hablé con mi madre.', sk: 'Včera som hovorila s mamou.', note: 'hablar → hablé' },
      { es: 'Comiste en casa.', sk: 'Jedla si doma.', note: 'comer → comiste' },
      { es: 'Salió a las ocho.', sk: 'Odišiel o ôsmej.', note: 'salir → salió' },
    ],
    tip: 'Použi indefinido pre ukončené deje: "Ayer fui", "La semana pasada compré".',
  },
  {
    id: 'gc-09',
    level: 'A2',
    category: 'pretérito indefinido',
    title: 'Minulý čas — nepravidelné: SER / IR / TENER',
    rule: 'SER a IR majú rovnaké tvary!\nfui, fuiste, fue, fuimos, fuisteis, fueron\nTENER: tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron',
    examples: [
      { es: 'Fui al cine.', sk: 'Išla som do kina.', note: 'ir → fui' },
      { es: 'Fue muy difícil.', sk: 'Bolo to veľmi ťažké.', note: 'ser → fue' },
      { es: 'Tuve un problema.', sk: 'Mala som problém.', note: 'tener → tuve' },
    ],
    tip: 'Kontext ti povie, či "fue" znamená "bol/bola" (ser) alebo "išiel/išla" (ir).',
  },
  {
    id: 'gc-10',
    level: 'A2',
    category: 'ir a + infinitivo',
    title: 'Budúcnosť: IR A + infinitív',
    rule: 'Použi "ir a + infinitív" pre plány v blízkej budúcnosti\n(podobne ako "going to" v angličtine)',
    examples: [
      { es: 'Voy a estudiar mañana.', sk: 'Zajtra budem študovať.', note: 'plán na zajtra' },
      { es: '¿Vas a venir?', sk: 'Prídeš?', note: 'otázka o plánoch' },
      { es: 'Va a llover.', sk: 'Bude pršať.', note: 'predpoveď' },
    ],
    tip: 'Toto je najčastejší spôsob, ako hovoriť o budúcnosti na úrovni A1/A2.',
  },
  {
    id: 'gc-11',
    level: 'A2',
    category: 'reflexivos',
    title: 'Zvratné slovesá — me, te, se...',
    rule: 'Zvratné zámeno ide pred časované sloveso\nalebo sa pripája k infinitívu',
    examples: [
      { es: 'Me llamo Ana.', sk: 'Volám sa Ana.', note: 'llamarse' },
      { es: 'Se levanta a las siete.', sk: 'Vstáva o siedmej.', note: 'levantarse' },
      { es: 'Voy a ducharme.', sk: 'Idem sa sprchovať.', note: 'pripojené k infinitívu' },
      { es: 'Nos acostamos tarde.', sk: 'Chodíme spať neskoro.', note: 'acostarse' },
    ],
    tip: 'Me / te / se / nos / os / se — zhoduj sa s podmetom.',
  },
  {
    id: 'gc-12',
    level: 'A2',
    category: 'desde hace',
    title: 'Trvanie: DESDE HACE',
    rule: '"Desde hace + čas" = už ... (prebiehajúca činnosť)\nPouži PRÍTOMNÝ čas — dej stále prebieha',
    examples: [
      { es: 'Estudio español desde hace seis meses.', sk: 'Študujem španielčinu šesť mesiacov.', note: 'prítomný čas + desde hace' },
      { es: 'Vivo aquí desde hace dos años.', sk: 'Bývam tu dva roky.', note: 'stále tam býva' },
    ],
    tip: 'Nikdy nepouži minulý čas s "desde hace", keď dej stále prebieha.',
  },
]
