// Grammar reference cards for A1/A2 Spanish learners

export const GRAMMAR_CARDS = [
  {
    id: 'gc-01',
    level: 'A1',
    category: 'ser / estar',
    title: 'SER vs ESTAR — the basics',
    rule: 'SER = permanent / identity\nESTAR = temporary / location / state',
    examples: [
      { es: 'Soy estudiante.', sk: 'Som študentka.', note: 'identity → ser' },
      { es: 'Estoy cansada.', sk: 'Som unavená.', note: 'temporary state → estar' },
      { es: 'Madrid está en España.', sk: 'Madrid je v Španielsku.', note: 'location → estar' },
      { es: 'El café es malo.', sk: 'Káva je zlá.', note: 'permanent quality → ser' },
    ],
    tip: 'If you can imagine it changing soon, use ESTAR.',
  },
  {
    id: 'gc-02',
    level: 'A1',
    category: 'tener',
    title: 'TENER expressions',
    rule: 'Many feelings use TENER + noun in Spanish\n(not SER/ESTAR + adjective like in Slovak/English)',
    examples: [
      { es: 'Tengo hambre.', sk: 'Mám hlad.', note: 'hunger' },
      { es: 'Tengo sed.', sk: 'Mám smäd.', note: 'thirst' },
      { es: 'Tengo frío / calor.', sk: 'Je mi zima / teplo.', note: 'temperature' },
      { es: 'Tengo miedo.', sk: 'Mám strach.', note: 'fear' },
      { es: 'Tengo sueño.', sk: 'Som ospalá.', note: 'sleepiness' },
    ],
    tip: 'Never say "Estoy hambre" — always "Tengo hambre".',
  },
  {
    id: 'gc-03',
    level: 'A1',
    category: 'gustar',
    title: 'GUSTAR — "to like"',
    rule: 'Subject and verb are reversed:\nThe thing liked is the subject → verb agrees with it',
    examples: [
      { es: 'Me gusta el café.', sk: 'Páči sa mi káva.', note: 'singular → gusta' },
      { es: 'Me gustan los gatos.', sk: 'Páčia sa mi mačky.', note: 'plural → gustan' },
      { es: 'Te gusta bailar.', sk: 'Páči sa ti tancovať.', note: 'infinitive → gusta' },
      { es: 'Le gusta mucho.', sk: 'Veľmi sa mu páči.', note: 'él/ella/usted' },
    ],
    tip: 'Ask: what is liked? If it\'s plural → gustan. If singular/infinitive → gusta.',
  },
  {
    id: 'gc-04',
    level: 'A1',
    category: 'artículos',
    title: 'Articles — el / la / los / las / un / una',
    rule: 'Every noun has a gender (masculine/feminine).\nel/un = masculine singular\nla/una = feminine singular\nlos/unos = masculine plural\nlas/unas = feminine plural',
    examples: [
      { es: 'el libro / un libro', sk: 'kniha (m.)', note: 'most -o words = masculine' },
      { es: 'la casa / una casa', sk: 'dom (f.)', note: 'most -a words = feminine' },
      { es: 'el día / el mapa', sk: 'výnimky — mužský rod', note: 'exceptions' },
      { es: 'la clase / la noche', sk: 'výnimky — ženský rod', note: 'exceptions ending in -e' },
    ],
    tip: 'Learn the article together with every new noun: "el trabajo", not just "trabajo".',
  },
  {
    id: 'gc-05',
    level: 'A1',
    category: 'presente',
    title: 'Present tense — regular verbs',
    rule: '-AR verbs: -o, -as, -a, -amos, -áis, -an\n-ER verbs: -o, -es, -e, -emos, -éis, -en\n-IR verbs: -o, -es, -e, -imos, -ís, -en',
    examples: [
      { es: 'Hablo / hablas / habla', sk: 'hovorím / hovoríš / hovorí', note: 'hablar (-AR)' },
      { es: 'Como / comes / come', sk: 'jem / ješ / je', note: 'comer (-ER)' },
      { es: 'Vivo / vives / vive', sk: 'bývam / bývaš / býva', note: 'vivir (-IR)' },
    ],
    tip: 'The yo form always ends in -o for regular verbs.',
  },
  {
    id: 'gc-06',
    level: 'A1',
    category: 'negación',
    title: 'Negation — NO',
    rule: 'Put NO directly before the verb.\nDouble negatives are correct in Spanish!',
    examples: [
      { es: 'No hablo inglés.', sk: 'Nehovorím po anglicky.', note: 'simple negation' },
      { es: 'No tengo nada.', sk: 'Nemám nič.', note: 'no + nada = double negative ✓' },
      { es: 'No voy nunca.', sk: 'Nikdy nechodím.', note: 'no + nunca ✓' },
      { es: 'No hay nadie aquí.', sk: 'Tu nie je nikto.', note: 'no + nadie ✓' },
    ],
    tip: 'Double negatives are REQUIRED in Spanish — "No tengo nada" is correct.',
  },
  {
    id: 'gc-07',
    level: 'A1',
    category: 'preposiciones',
    title: 'Key prepositions: A, EN, DE',
    rule: 'A = to / at (direction, time)\nEN = in / on (location, means of transport)\nDE = of / from (origin, possession)',
    examples: [
      { es: 'Voy a Madrid.', sk: 'Idem do Madridu.', note: 'a = direction' },
      { es: 'Vivo en España.', sk: 'Bývam v Španielsku.', note: 'en = location' },
      { es: 'Soy de Eslovaquia.', sk: 'Som zo Slovenska.', note: 'de = origin' },
      { es: 'Voy en metro.', sk: 'Idem metrom.', note: 'en = transport' },
    ],
    tip: '"A pie" (on foot) and "en coche" (by car) — learn these as fixed phrases.',
  },
  {
    id: 'gc-08',
    level: 'A2',
    category: 'pretérito indefinido',
    title: 'Past tense (pretérito indefinido) — regular',
    rule: '-AR: -é, -aste, -ó, -amos, -asteis, -aron\n-ER/-IR: -í, -iste, -ió, -imos, -isteis, -ieron',
    examples: [
      { es: 'Ayer hablé con mi madre.', sk: 'Včera som hovorila s mamou.', note: 'hablar → hablé' },
      { es: 'Comiste en casa.', sk: 'Jedla si doma.', note: 'comer → comiste' },
      { es: 'Salió a las ocho.', sk: 'Odišiel o ôsmej.', note: 'salir → salió' },
    ],
    tip: 'Use indefinido for completed actions: "Ayer fui", "La semana pasada compré".',
  },
  {
    id: 'gc-09',
    level: 'A2',
    category: 'pretérito indefinido',
    title: 'Past tense — irregular: SER / IR / TENER',
    rule: 'SER and IR share the same forms!\nfui, fuiste, fue, fuimos, fuisteis, fueron\nTENER: tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron',
    examples: [
      { es: 'Fui al cine.', sk: 'Išla som do kina.', note: 'ir → fui' },
      { es: 'Fue muy difícil.', sk: 'Bolo to veľmi ťažké.', note: 'ser → fue' },
      { es: 'Tuve un problema.', sk: 'Mala som problém.', note: 'tener → tuve' },
    ],
    tip: 'Context tells you if "fue" means "was" (ser) or "went" (ir).',
  },
  {
    id: 'gc-10',
    level: 'A2',
    category: 'ir a + infinitivo',
    title: 'Future: IR A + infinitive',
    rule: 'Use "ir a + infinitive" for near future plans\n(like "going to" in English)',
    examples: [
      { es: 'Voy a estudiar mañana.', sk: 'Zajtra budem študovať.', note: 'plan for tomorrow' },
      { es: '¿Vas a venir?', sk: 'Prídeš?', note: 'question about plans' },
      { es: 'Va a llover.', sk: 'Bude pršať.', note: 'prediction' },
    ],
    tip: 'This is the most common way to talk about the future at A1/A2 level.',
  },
  {
    id: 'gc-11',
    level: 'A2',
    category: 'reflexivos',
    title: 'Reflexive verbs — me, te, se...',
    rule: 'Reflexive pronoun goes before the conjugated verb\nor attached to the infinitive',
    examples: [
      { es: 'Me llamo Ana.', sk: 'Volám sa Ana.', note: 'llamarse' },
      { es: 'Se levanta a las siete.', sk: 'Vstáva o siedmej.', note: 'levantarse' },
      { es: 'Voy a ducharme.', sk: 'Idem sa sprchovať.', note: 'attached to infinitive' },
      { es: 'Nos acostamos tarde.', sk: 'Chodíme spať neskoro.', note: 'acostarse' },
    ],
    tip: 'Me / te / se / nos / os / se — match the subject.',
  },
  {
    id: 'gc-12',
    level: 'A2',
    category: 'desde hace',
    title: 'Duration: DESDE HACE',
    rule: '"Desde hace + time" = for (an ongoing action)\nUse PRESENT tense — action still continues',
    examples: [
      { es: 'Estudio español desde hace seis meses.', sk: 'Študujem španielčinu šesť mesiacov.', note: 'present + desde hace' },
      { es: 'Vivo aquí desde hace dos años.', sk: 'Bývam tu dva roky.', note: 'still living there' },
    ],
    tip: 'Never use past tense with "desde hace" when the action is still ongoing.',
  },
]