export const LISTENING_EXERCISES = [
  { sentence: 'Me llamo Ana y soy ___ España.', missingWord: 'de', options: ['de', 'en', 'a', 'por'], explanation: '"Ser de" indicates origin.' },
  { sentence: 'Tengo veintidós ___ y estudio español.', missingWord: 'años', options: ['años', 'dias', 'meses', 'semanas'], explanation: '"Tener X años" = to be X years old.' },
  { sentence: 'Me gusta mucho el ___ por la mañana.', missingWord: 'café', options: ['café', 'agua', 'libro', 'trabajo'], explanation: '"El café por la mañana" is very common in Spanish culture.' },
  { sentence: 'Vivo ___ una ciudad pequeña pero bonita.', missingWord: 'en', options: ['en', 'a', 'de', 'con'], explanation: '"Vivir en" = to live in (location).' },
  { sentence: '¿A qué hora ___ levantes normalmente?', missingWord: 'te', options: ['te', 'se', 'me', 'le'], explanation: '"Levantarse" is reflexive: ¿A qué hora te levantas?' },
  { sentence: 'Trabajo de lunes a ___ en una oficina.', missingWord: 'viernes', options: ['viernes', 'sábado', 'domingo', 'jueves'], explanation: '"De lunes a viernes" = Monday to Friday.' },
  { sentence: 'Quiero ___ español para viajar a México.', missingWord: 'aprender', options: ['aprender', 'enseñar', 'escribir', 'leer'], explanation: '"Quiero aprender" = I want to learn.' },
  { sentence: 'Mi ___ es muy importante para mí.', missingWord: 'familia', options: ['familia', 'trabajo', 'dinero', 'ciudad'], explanation: '"Mi familia" = my family.' },
  { sentence: 'Ayer ___ al supermercado con mi madre.', missingWord: 'fui', options: ['fui', 'voy', 'iba', 'iré'], explanation: '"Fui" is the preterite of "ir": I went.' },
  { sentence: 'El español es difícil pero muy ___.', missingWord: 'interesante', options: ['interesante', 'aburrido', 'fácil', 'rápido'], explanation: 'A common opinion about Spanish!' },
  { sentence: 'Me ___ a las siete de la mañana.', missingWord: 'levanto', options: ['levanto', 'duermo', 'desayuno', 'acuesto'], explanation: '"Me levanto" = I get up (reflexive verb).' },
  { sentence: 'Esta semana tengo mucho ___.', missingWord: 'trabajo', options: ['trabajo', 'sueño', 'hambre', 'libro'], explanation: '"Tengo mucho trabajo" = I have a lot of work.' },
  { sentence: '¿Dónde ___ tú ahora mismo?', missingWord: 'vives', options: ['vives', 'eres', 'tienes', 'comes'], explanation: '"¿Dónde vives?" = Where do you live?' },
  { sentence: 'Me encanta la ___ española.', missingWord: 'comida', options: ['comida', 'música', 'lengua', 'cultura'], explanation: '"La comida española" = Spanish food.' },
  { sentence: 'Mañana voy a ir ___ médico.', missingWord: 'al', options: ['al', 'del', 'el', 'un'], explanation: '"Ir al médico" = to go to the doctor. A + el = al.' },
  { sentence: 'Los fines de semana me gusta ___ con amigos.', missingWord: 'quedar', options: ['quedar', 'trabajar', 'estudiar', 'dormir'], explanation: '"Quedar con amigos" = to meet up with friends.' },
  { sentence: 'No me gusta el tiempo ___ en invierno.', missingWord: 'frío', options: ['frío', 'caliente', 'bonito', 'nuevo'], explanation: '"El tiempo frío" = cold weather.' },
  { sentence: 'Hablo ___ poco de inglés también.', missingWord: 'un', options: ['un', 'una', 'unos', 'mucho'], explanation: '"Un poco de" = a little bit of.' },
  { sentence: '¿Puedes hablar más ___, por favor?', missingWord: 'despacio', options: ['despacio', 'rápido', 'bien', 'mucho'], explanation: '"Hablar más despacio" = to speak more slowly.' },
  { sentence: 'El fin de semana pasado ___ en casa.', missingWord: 'estuve', options: ['estuve', 'fui', 'hice', 'tuve'], explanation: '"Estuve en casa" = I stayed at home. Preterite of "estar".' },
]