export const SENTENCE_REORDER_EXERCISES = [
  { words: ['Me', 'llamo', 'Ana', 'y', 'soy', 'de', 'España'], answer: 'Me llamo Ana y soy de España', translation: 'Volám sa Ana a som zo Španielska.' },
  { words: ['Tengo', 'veintidós', 'años', 'y', 'estudio', 'español'], answer: 'Tengo veintidós años y estudio español', translation: 'Mám dvadsaťdva rokov a študujem španielčinu.' },
  { words: ['Me', 'gusta', 'mucho', 'el', 'café', 'por', 'la', 'mañana'], answer: 'Me gusta mucho el café por la mañana', translation: 'Ráno sa mi veľmi páči káva.' },
  { words: ['Vivo', 'en', 'una', 'ciudad', 'pequeña', 'pero', 'bonita'], answer: 'Vivo en una ciudad pequeña pero bonita', translation: 'Bývam v malom ale peknom meste.' },
  { words: ['¿A', 'qué', 'hora', 'te', 'levantas', 'normalmente'], answer: '¿A qué hora te levantas normalmente?', translation: 'O koľkej sa normálne vstávaš?' },
  { words: ['Los', 'fines', 'de', 'semana', 'me', 'gusta', 'salir', 'con', 'amigos'], answer: 'Los fines de semana me gusta salir con amigos', translation: 'Cez víkendy rád/a chodím von s priateľmi.' },
  { words: ['Trabajo', 'de', 'lunes', 'a', 'viernes', 'en', 'una', 'oficina'], answer: 'Trabajo de lunes a viernes en una oficina', translation: 'Pracujem od pondelka do piatku v kancelárii.' },
  { words: ['Quiero', 'aprender', 'español', 'para', 'viajar', 'a', 'México'], answer: 'Quiero aprender español para viajar a México', translation: 'Chcem sa naučiť španielčinu, aby som mohol/a cestovať do Mexika.' },
  { words: ['¿Cuántos', 'hermanos', 'tienes', 'tú'], answer: '¿Cuántos hermanos tienes tú?', translation: 'Koľko súrodencov máš?' },
  { words: ['Mi', 'familia', 'es', 'muy', 'importante', 'para', 'mí'], answer: 'Mi familia es muy importante para mí', translation: 'Moja rodina je pre mňa veľmi dôležitá.' },
  { words: ['Ayer', 'fui', 'al', 'supermercado', 'con', 'mi', 'madre'], answer: 'Ayer fui al supermercado con mi madre', translation: 'Včera som išiel/išla do supermarketu s mamou.' },
  { words: ['No', 'me', 'gusta', 'el', 'tiempo', 'frío', 'en', 'invierno'], answer: 'No me gusta el tiempo frío en invierno', translation: 'Nepáči sa mi studené počasie v zime.' },
  { words: ['Esta', 'semana', 'tengo', 'mucho', 'trabajo'], answer: 'Esta semana tengo mucho trabajo', translation: 'Tento týždeň mám veľa práce.' },
  { words: ['¿Puedes', 'hablar', 'más', 'despacio', 'por', 'favor'], answer: '¿Puedes hablar más despacio, por favor?', translation: 'Môžeš hovoriť pomalšie, prosím?' },
  { words: ['El', 'español', 'es', 'difícil', 'pero', 'muy', 'interesante'], answer: 'El español es difícil pero muy interesante', translation: 'Španielčina je ťažká, ale veľmi zaujímavá.' },
  { words: ['Mañana', 'voy', 'a', 'ir', 'al', 'médico'], answer: 'Mañana voy a ir al médico', translation: 'Zajtra pôjdem k lekárovi.' },
  { words: ['Me', 'levanto', 'a', 'las', 'siete', 'de', 'la', 'mañana'], answer: 'Me levanto a las siete de la mañana', translation: 'Vstávam o siedmej ráno.' },
  { words: ['¿Dónde', 'vives', 'tú', 'ahora', 'mismo'], answer: '¿Dónde vives tú ahora mismo?', translation: 'Kde momentálne bývaš?' },
  { words: ['Me', 'encanta', 'la', 'comida', 'española'], answer: 'Me encanta la comida española', translation: 'Milujem španielske jedlo.' },
  { words: ['El', 'fin', 'de', 'semana', 'pasado', 'estuve', 'en', 'casa'], answer: 'El fin de semana pasado estuve en casa', translation: 'Minulý víkend som bol/bola doma.' },
]