// Thematic vocabulary packs for A1/A2 Spanish learners

export const VOCABULARY_PACKS = [
  {
    id: 'pack-restaurant',
    title: 'V reštaurácii',
    emoji: '🍽️',
    level: 'A1',
    words: [
      { es: 'la mesa', sk: 'stôl' },
      { es: 'la silla', sk: 'stolička' },
      { es: 'el menú', sk: 'jedálny lístok' },
      { es: 'el camarero / la camarera', sk: 'čašník / čašníčka' },
      { es: 'la cuenta', sk: 'účet' },
      { es: 'el plato', sk: 'jedlo / tanier' },
      { es: 'la bebida', sk: 'nápoj' },
      { es: 'el postre', sk: 'dezert' },
      { es: 'la propina', sk: 'prepitné' },
      { es: 'pedir', sk: 'objednať si' },
      { es: 'reservar', sk: 'rezervovať' },
      { es: '¿Me trae...?', sk: 'Môžete mi priniesť...?' },
      { es: 'La cuenta, por favor.', sk: 'Účet, prosím.' },
      { es: '¿Qué recomienda?', sk: 'Čo odporúčate?' },
      { es: 'Estaba muy rico.', sk: 'Bolo to veľmi chutné.' },
    ],
  },
  {
    id: 'pack-shopping',
    title: 'Nakupovanie',
    emoji: '🛒',
    level: 'A1',
    words: [
      { es: 'la tienda', sk: 'obchod' },
      { es: 'el supermercado', sk: 'supermarket' },
      { es: 'el precio', sk: 'cena' },
      { es: 'caro / barato', sk: 'drahý / lacný' },
      { es: 'la talla', sk: 'veľkosť (oblečenie)' },
      { es: 'el probador', sk: 'skúšobná kabínka' },
      { es: '¿Cuánto cuesta?', sk: 'Koľko to stojí?' },
      { es: '¿Tiene en otra talla?', sk: 'Máte v inej veľkosti?' },
      { es: 'Voy a llevar esto.', sk: 'Vezmem si toto.' },
      { es: 'pagar', sk: 'zaplatiť' },
      { es: 'la tarjeta / el efectivo', sk: 'karta / hotovosť' },
      { es: 'el recibo', sk: 'pokladničný blok' },
      { es: 'la oferta', sk: 'akcia / výpredaj' },
      { es: 'el descuento', sk: 'zľava' },
      { es: 'la bolsa', sk: 'taška' },
    ],
  },
  {
    id: 'pack-family',
    title: 'Rodina',
    emoji: '👨‍👩‍👧',
    level: 'A1',
    words: [
      { es: 'el padre / la madre', sk: 'otec / matka' },
      { es: 'el hermano / la hermana', sk: 'brat / sestra' },
      { es: 'el abuelo / la abuela', sk: 'starý otec / stará mama' },
      { es: 'el hijo / la hija', sk: 'syn / dcéra' },
      { es: 'el tío / la tía', sk: 'strýko / teta' },
      { es: 'el primo / la prima', sk: 'bratranec / sesternica' },
      { es: 'el marido / la mujer', sk: 'manžel / manželka' },
      { es: 'el novio / la novia', sk: 'priateľ / priateľka' },
      { es: 'los padres', sk: 'rodičia' },
      { es: 'los abuelos', sk: 'starí rodičia' },
      { es: 'mayor / menor', sk: 'starší / mladší' },
      { es: 'único/a', sk: 'jedináčik' },
      { es: 'gemelos/as', sk: 'dvojičky' },
      { es: 'llevarse bien', sk: 'vychádzať si dobre' },
      { es: 'parecerse a', sk: 'podobať sa na' },
    ],
  },
  {
    id: 'pack-numbers',
    title: 'Čísla a čas',
    emoji: '🕐',
    level: 'A1',
    words: [
      { es: 'uno, dos, tres, cuatro, cinco', sk: 'jeden, dva, tri, štyri, päť' },
      { es: 'seis, siete, ocho, nueve, diez', sk: 'šesť, sedem, osem, deväť, desať' },
      { es: 'veinte / treinta / cuarenta / cincuenta', sk: 'dvadsať / tridsať / štyridsať / päťdesiat' },
      { es: 'cien / doscientos / mil', sk: 'sto / dvesto / tisíc' },
      { es: '¿Qué hora es?', sk: 'Koľko je hodín?' },
      { es: 'Son las tres.', sk: 'Sú tri hodiny.' },
      { es: 'Es la una y media.', sk: 'Je pol druhej.' },
      { es: 'a las ocho en punto', sk: 'o ôsmej presne' },
      { es: 'por la mañana / tarde / noche', sk: 'ráno / popoludní / večer' },
      { es: 'lunes, martes, miércoles', sk: 'pondelok, utorok, streda' },
      { es: 'jueves, viernes, sábado, domingo', sk: 'štvrtok, piatok, sobota, nedeľa' },
      { es: 'enero, febrero, marzo, abril', sk: 'január, február, marec, apríl' },
      { es: 'mayo, junio, julio, agosto', sk: 'máj, jún, júl, august' },
      { es: 'septiembre, octubre, noviembre, diciembre', sk: 'september, október, november, december' },
      { es: '¿Qué día es hoy?', sk: 'Aký je dnes deň?' },
    ],
  },
  {
    id: 'pack-travel',
    title: 'Cestovanie',
    emoji: '✈️',
    level: 'A2',
    words: [
      { es: 'el aeropuerto', sk: 'letisko' },
      { es: 'el vuelo', sk: 'let' },
      { es: 'la maleta', sk: 'kufor' },
      { es: 'el billete / el boleto', sk: 'lístok / cestovný lístok' },
      { es: 'la estación', sk: 'stanica' },
      { es: 'el andén', sk: 'nástupište' },
      { es: 'facturar el equipaje', sk: 'odbavenie batožiny' },
      { es: 'la aduana', sk: 'colnica' },
      { es: 'el pasaporte', sk: 'pas' },
      { es: 'el alojamiento', sk: 'ubytovanie' },
      { es: 'la habitación doble / individual', sk: 'dvojlôžková / jednolôžková izba' },
      { es: 'el desayuno incluido', sk: 'raňajky v cene' },
      { es: 'perder el tren', sk: 'zmeškať vlak' },
      { es: '¿Dónde está...?', sk: 'Kde je...?' },
      { es: 'Me he perdido.', sk: 'Stratila som sa.' },
    ],
  },
  {
    id: 'pack-health',
    title: 'Zdravie',
    emoji: '🏥',
    level: 'A2',
    words: [
      { es: 'el médico / la médica', sk: 'lekár / lekárka' },
      { es: 'la farmacia', sk: 'lekáreň' },
      { es: 'el medicamento', sk: 'liek' },
      { es: 'me duele la cabeza', sk: 'bolí ma hlava' },
      { es: 'tengo fiebre', sk: 'mám horúčku' },
      { es: 'estoy resfriada', sk: 'som prechladnutá' },
      { es: 'la cita', sk: 'termín u lekára' },
      { es: 'el seguro médico', sk: 'zdravotné poistenie' },
      { es: 'la receta', sk: 'recept' },
      { es: 'pedir hora', sk: 'objednať sa k lekárovi' },
      { es: 'el hospital', sk: 'nemocnica' },
      { es: 'la urgencia', sk: 'pohotovosť' },
      { es: 'el dolor de estómago', sk: 'bolesť brucha' },
      { es: 'tomar pastillas', sk: 'brať tabletky' },
      { es: '¿Qué le pasa?', sk: 'Čo vám je?' },
    ],
  },
]