// Word of the Day — 60 curated B1/B2/C1 English words for Slovak learners
// Selected daily: Math.floor(Date.now() / 86400000) % WORDS.length

export const WORDS_OF_DAY = [
  { word: 'resilient',      level: 'B2', sk: 'odolný',                  definition: 'Able to recover quickly from difficulties; tough.', example: 'She is incredibly resilient — she bounced back from every setback.' },
  { word: 'ambiguous',      level: 'B2', sk: 'nejednoznačný',            definition: 'Open to more than one interpretation; unclear.', example: 'His answer was ambiguous, so nobody knew what he really meant.' },
  { word: 'diligent',       level: 'B2', sk: 'usilovný',                 definition: 'Having or showing care and effort in your work.', example: 'She was a diligent student who never missed a deadline.' },
  { word: 'forthcoming',    level: 'B2', sk: 'ochotný / nadchádzajúci',  definition: 'About to happen; or willing to give information.', example: 'He was not very forthcoming about why he left the job.' },
  { word: 'eloquent',       level: 'B2', sk: 'výrečný',                  definition: 'Fluent and persuasive in speaking or writing.', example: 'Her speech was so eloquent that the whole room fell silent.' },
  { word: 'inevitable',     level: 'B2', sk: 'nevyhnutný',               definition: 'Certain to happen; unable to be avoided.', example: 'Change is inevitable — the question is how you respond to it.' },
  { word: 'trivial',        level: 'B1', sk: 'bezvýznamný',              definition: 'Of little value or importance; small.', example: 'Don\'t waste energy on trivial things that don\'t really matter.' },
  { word: 'candid',         level: 'B2', sk: 'úprimný / priamočiary',    definition: 'Truthful and straightforward; frank.', example: 'I appreciated her candid feedback — it helped me improve.' },
  { word: 'meticulous',     level: 'B2', sk: 'precízny / dôkladný',      definition: 'Showing great attention to detail; very careful.', example: 'He was meticulous about checking every word before sending the email.' },
  { word: 'adamant',        level: 'B2', sk: 'neoblomný',                definition: 'Refusing to be persuaded; firm and determined.', example: 'She was adamant that she hadn\'t made a mistake.' },
  { word: 'subtle',         level: 'B2', sk: 'jemný / nenápadný',        definition: 'So delicate or precise as to be difficult to detect.', example: 'There was a subtle difference in tone that most people missed.' },
  { word: 'compelling',     level: 'B2', sk: 'presvedčivý / pútavý',     definition: 'Evoking interest, attention, or admiration in a powerful way.', example: 'The documentary made a compelling case for changing our habits.' },
  { word: 'oblivious',      level: 'B2', sk: 'neuvedomujúci si',         definition: 'Not aware of or not concerned about what is happening.', example: 'He walked in, completely oblivious to the tension in the room.' },
  { word: 'pragmatic',      level: 'C1', sk: 'pragmatický',              definition: 'Dealing with things sensibly and realistically.', example: 'We need a pragmatic solution, not just an idealistic one.' },
  { word: 'concise',        level: 'B2', sk: 'stručný',                  definition: 'Giving a lot of information clearly in few words.', example: 'Please keep your answer concise — we have limited time.' },
  { word: 'versatile',      level: 'B2', sk: 'všestranný',               definition: 'Able to adapt or be adapted to many different functions.', example: 'She is a versatile performer — she can sing, act, and dance.' },
  { word: 'defer',          level: 'C1', sk: 'odložiť / podriadiť sa',   definition: 'To put off to a later time; or to submit to another\'s opinion.', example: 'We had to defer the meeting until everyone was available.' },
  { word: 'lucid',          level: 'C1', sk: 'jasný / zrozumiteľný',     definition: 'Expressed clearly; easy to understand.', example: 'His explanation was so lucid that even I understood it immediately.' },
  { word: 'repercussion',   level: 'B2', sk: 'dôsledok / dosah',         definition: 'An unintended consequence of an event or action.', example: 'The decision had serious repercussions for the whole team.' },
  { word: 'alleviate',      level: 'C1', sk: 'zmierniť / uľaviť',        definition: 'To make suffering or a problem less severe.', example: 'A short walk can alleviate stress more than you might think.' },
  { word: 'tentative',      level: 'B2', sk: 'predbežný / váhavý',       definition: 'Not certain or fixed; provisional; hesitant.', example: 'We made a tentative plan, but nothing is confirmed yet.' },
  { word: 'impartial',      level: 'B2', sk: 'nestranný',                definition: 'Treating all rivals or disputants equally; fair.', example: 'A good judge must remain impartial throughout the trial.' },
  { word: 'stagnant',       level: 'B2', sk: 'stagnujúci',               definition: 'Not flowing or moving; showing no activity or growth.', example: 'Without new challenges, your skills can quickly become stagnant.' },
  { word: 'reciprocal',     level: 'C1', sk: 'vzájomný',                 definition: 'Given, felt, or done in return; mutual.', example: 'A good friendship is reciprocal — both people make an effort.' },
  { word: 'coherent',       level: 'B2', sk: 'súdržný / logický',        definition: 'Logical and consistent; clearly articulated.', example: 'Her argument was coherent and well-supported by evidence.' },
  { word: 'persist',        level: 'B1', sk: 'pretrvávať / nevzdávať sa', definition: 'To continue firmly despite difficulty or opposition.', example: 'If you persist, you will eventually see results.' },
  { word: 'vague',          level: 'B1', sk: 'nejasný',                  definition: 'Not clearly expressed or understood; imprecise.', example: 'His instructions were too vague — nobody knew what to do.' },
  { word: 'empathy',        level: 'B2', sk: 'empatia',                  definition: 'The ability to understand and share the feelings of another.', example: 'Good teachers have a lot of empathy for their students.' },
  { word: 'prejudice',      level: 'B2', sk: 'predsudok',                definition: 'Preconceived opinion not based on reason or experience.', example: 'We all have some prejudices — the key is to be aware of them.' },
  { word: 'integrity',      level: 'B2', sk: 'integrita / čestnosť',     definition: 'The quality of being honest and having strong moral principles.', example: 'She is known for her integrity — you can always trust her word.' },
  { word: 'notorious',      level: 'B2', sk: 'neslávne známy',           definition: 'Famous or well-known, typically for bad reasons.', example: 'The area is notorious for its heavy traffic at rush hour.' },
  { word: 'spontaneous',    level: 'B2', sk: 'spontánny',                definition: 'Performed or occurring without premeditation; natural.', example: 'They made a spontaneous decision to drive to the coast.' },
  { word: 'deteriorate',    level: 'B2', sk: 'zhoršovať sa',             definition: 'To become progressively worse.', example: 'His health began to deteriorate after the long hospital stay.' },
  { word: 'nuance',         level: 'C1', sk: 'odtienok / nuansa',        definition: 'A subtle difference in meaning, tone, or expression.', example: 'Language learners often miss the nuances that make speech natural.' },
  { word: 'leverage',       level: 'C1', sk: 'využiť / páka',            definition: 'To use something to maximum advantage.', example: 'She leveraged her experience to land a much better job.' },
  { word: 'incentive',      level: 'B2', sk: 'stimul / motivácia',       definition: 'A thing that motivates or encourages someone to do something.', example: 'The bonus was a strong incentive to work harder.' },
  { word: 'ambivalent',     level: 'C1', sk: 'ambivalentný',             definition: 'Having mixed or contradictory feelings about something.', example: 'I feel ambivalent about moving — excited but also nervous.' },
  { word: 'cynical',        level: 'B2', sk: 'cynický',                  definition: 'Believing that people are motivated only by self-interest.', example: 'He became cynical after years of broken promises.' },
  { word: 'feasible',       level: 'B2', sk: 'uskutočniteľný',           definition: 'Possible and practical to do easily or conveniently.', example: 'Is it feasible to finish this by Friday? It\'s a lot of work.' },
  { word: 'detrimental',    level: 'C1', sk: 'škodlivý',                 definition: 'Tending to cause harm or damage.', example: 'Lack of sleep is detrimental to both your mood and memory.' },
  { word: 'insightful',     level: 'B2', sk: 'prezieravý / poučný',      definition: 'Having or showing a deep understanding of something.', example: 'Her insightful comments really made me think differently.' },
  { word: 'flawed',         level: 'B2', sk: 'chybný / nedokonalý',      definition: 'Having or characterised by a fundamental weakness or imperfection.', example: 'The plan was clever but flawed — it relied on too many assumptions.' },
  { word: 'innate',         level: 'C1', sk: 'vrodený',                  definition: 'Inborn; natural; not learned.', example: 'Some people seem to have an innate talent for languages.' },
  { word: 'apprehensive',   level: 'B2', sk: 'úzkostlivý / obávajúci sa', definition: 'Anxious or fearful that something bad will happen.', example: 'She was apprehensive about her first day at the new job.' },
  { word: 'articulate',     level: 'B2', sk: 'výrečný / jasne sa vyjadrujúci', definition: 'Having or showing the ability to speak fluently and coherently.', example: 'He is very articulate — he always finds the right words.' },
  { word: 'paramount',      level: 'C1', sk: 'najdôležitejší',           definition: 'More important than anything else; supreme.', example: 'Your safety is of paramount importance on this trip.' },
  { word: 'momentum',       level: 'B2', sk: 'hybná sila / tempo',       definition: 'The quantity of motion of a moving body; impetus gained by movement.', example: 'Once you build momentum with a habit, it gets easier to maintain.' },
  { word: 'proactive',      level: 'B2', sk: 'proaktívny',               definition: 'Creating or controlling a situation rather than just responding.', example: 'A proactive approach means solving problems before they grow.' },
  { word: 'fluctuate',      level: 'B2', sk: 'kolísať',                  definition: 'To rise and fall irregularly in number or amount.', example: 'Her motivation fluctuates — some days great, some days not.' },
  { word: 'contemplate',    level: 'B2', sk: 'uvažovať / rozjímať',      definition: 'To think profoundly and at length; consider carefully.', example: 'Take a moment to contemplate what you really want from this.' },
  { word: 'elusive',        level: 'C1', sk: 'neuchopiteľný / ťažko dosiahnuteľný', definition: 'Difficult to find, catch, or achieve.', example: 'Fluency can feel elusive, but it comes with consistent practice.' },
  { word: 'tangible',       level: 'C1', sk: 'hmatateľný / konkrétny',   definition: 'Perceptible by touch; clear and definite; real.', example: 'After six months of study, she saw tangible improvement.' },
  { word: 'acknowledge',    level: 'B2', sk: 'uznať / pripustiť',        definition: 'To accept or admit the existence or truth of something.', example: 'It is important to acknowledge your mistakes and learn from them.' },
  { word: 'transparent',    level: 'B2', sk: 'transparentný / otvorený', definition: 'Easy to see through or understand; open and honest.', example: 'Good leaders are transparent about their decisions.' },
  { word: 'scrutinise',     level: 'C1', sk: 'dôkladne preskúmať',       definition: 'To examine or inspect closely and thoroughly.', example: 'The committee will scrutinise every aspect of the proposal.' },
  { word: 'chronic',        level: 'B2', sk: 'chronický',                definition: 'Persisting for a long time; constantly recurring.', example: 'Chronic stress has serious long-term effects on your health.' },
  { word: 'plausible',      level: 'C1', sk: 'hodnoverný / uveriteľný',  definition: 'Seeming reasonable or probable; credible.', example: 'Her excuse was plausible, but something still felt off.' },
  { word: 'indispensable',  level: 'C1', sk: 'nenahraditeľný / nevyhnutný', definition: 'Absolutely necessary; essential.', example: 'Good communication skills are indispensable in any job.' },
  { word: 'discrepancy',    level: 'C1', sk: 'nezrovnalosť / nesúlad',   definition: 'An illogical or surprising lack of compatibility between things.', example: 'There is a discrepancy between what he said and what he did.' },
  { word: 'undermine',      level: 'B2', sk: 'podkopávať / oslabiť',     definition: 'To erode the base or foundation of; weaken.', example: 'Self-doubt can undermine your confidence if you let it.' },
  { word: 'perceive',       level: 'B2', sk: 'vnímať / uvedomiť si',     definition: 'To become aware of through the senses; to understand.', example: 'How you perceive a situation shapes how you feel about it.' },
]

export function getWordOfDay() {
  const dayIndex = Math.floor(Date.now() / 86400000)
  return WORDS_OF_DAY[dayIndex % WORDS_OF_DAY.length]
}
