// Word of the Day — 60 curated A1/A2 Spanish words for Slovak learners
// Selected daily: Math.floor(Date.now() / 86400000) % WORDS.length

export const WORDS_OF_DAY = [
  { word: 'hablar',    level: 'A1', sk: 'hovoriť',           definition: 'To speak or talk.',              example: 'Me gusta hablar español con mis amigos.' },
  { word: 'comer',     level: 'A1', sk: 'jesť',              definition: 'To eat.',                        example: 'Comemos juntos en familia todos los días.' },
  { word: 'vivir',     level: 'A1', sk: 'žiť / bývať',       definition: 'To live.',                       example: 'Vivo en un apartamento pequeño en el centro.' },
  { word: 'querer',    level: 'A1', sk: 'chcieť / milovať',  definition: 'To want; to love.',              example: 'Quiero aprender español bien.' },
  { word: 'poder',     level: 'A1', sk: 'môcť',              definition: 'To be able to; can.',            example: '¿Puedes ayudarme con esto?' },
  { word: 'ir',        level: 'A1', sk: 'ísť',               definition: 'To go.',                        example: 'Voy al supermercado los sábados.' },
  { word: 'trabajar',  level: 'A1', sk: 'pracovať',          definition: 'To work.',                       example: 'Trabajo en una oficina de lunes a viernes.' },
  { word: 'estudiar',  level: 'A1', sk: 'študovať',          definition: 'To study.',                      example: 'Estudio español todos los días.' },
  { word: 'saber',     level: 'A1', sk: 'vedieť',            definition: 'To know a fact or skill.',       example: '¿Sabes dónde está la farmacia?' },
  { word: 'conocer',   level: 'A1', sk: 'poznať',            definition: 'To know a person or place.',     example: 'Conozco a una chica que habla cuatro idiomas.' },
  { word: 'tener',     level: 'A1', sk: 'mať',               definition: 'To have.',                       example: 'Tengo una reunión importante mañana.' },
  { word: 'hacer',     level: 'A1', sk: 'robiť',             definition: 'To do or make.',                 example: '¿Qué haces los fines de semana?' },
  { word: 'casa',      level: 'A1', sk: 'dom',               definition: 'Home or house.',                 example: 'Me encanta pasar tiempo en casa los domingos.' },
  { word: 'tiempo',    level: 'A1', sk: 'čas / počasie',     definition: 'Time or weather.',               example: 'No tengo tiempo para cocinar hoy.' },
  { word: 'año',       level: 'A1', sk: 'rok',               definition: 'Year.',                          example: 'El año pasado viajé a Portugal.' },
  { word: 'día',       level: 'A1', sk: 'deň',               definition: 'Day.',                           example: '¿Qué hiciste el día de tu cumpleaños?' },
  { word: 'ciudad',    level: 'A1', sk: 'mesto',             definition: 'City.',                          example: 'Barcelona es una ciudad increíble.' },
  { word: 'trabajo',   level: 'A1', sk: 'práca',             definition: 'Work; job.',                     example: 'Me gusta mucho mi trabajo.' },
  { word: 'amigo',     level: 'A1', sk: 'priateľ',           definition: 'Friend.',                        example: 'Mi mejor amiga vive en otra ciudad.' },
  { word: 'familia',   level: 'A1', sk: 'rodina',            definition: 'Family.',                        example: 'La familia es lo más importante para mí.' },
  { word: 'escuela',   level: 'A1', sk: 'škola',             definition: 'School.',                        example: 'Mis hijos van a la escuela cerca de casa.' },
  { word: 'comida',    level: 'A1', sk: 'jedlo',             definition: 'Food; meal.',                    example: 'La comida española me parece deliciosa.' },
  { word: 'dinero',    level: 'A1', sk: 'peniaze',           definition: 'Money.',                         example: 'No tengo mucho dinero este mes.' },
  { word: 'noche',     level: 'A1', sk: 'noc',               definition: 'Night; evening.',                example: 'Nos vemos por la noche en el restaurante.' },
  { word: 'tarde',     level: 'A1', sk: 'popoludnie',        definition: 'Afternoon.',                     example: 'Llegó tarde — eran las tres de la tarde.' },
  { word: 'libro',     level: 'A1', sk: 'kniha',             definition: 'Book.',                          example: 'Estoy leyendo un libro muy interesante.' },
  { word: 'agua',      level: 'A1', sk: 'voda',              definition: 'Water.',                         example: '¿Me puedes traer un vaso de agua, por favor?' },
  { word: 'hora',      level: 'A1', sk: 'hodina / čas',      definition: 'Hour; time (clock).',            example: '¿Qué hora es? Tengo que salir pronto.' },
  { word: 'niño',      level: 'A1', sk: 'dieťa / chlapec',   definition: 'Child; boy.',                    example: 'El niño de mis vecinos aprende a tocar el piano.' },
  { word: 'mujer',     level: 'A1', sk: 'žena',              definition: 'Woman.',                         example: 'La mujer que vive al lado trabaja de médica.' },
  { word: 'hombre',    level: 'A1', sk: 'muž',               definition: 'Man.',                           example: 'El hombre que vino ayer era muy amable.' },
  { word: 'mañana',    level: 'A1', sk: 'ráno / zajtra',     definition: 'Morning; tomorrow.',             example: 'Mañana por la mañana tengo que madrugar.' },
  { word: 'siempre',   level: 'A1', sk: 'vždy',              definition: 'Always.',                        example: 'Siempre desayuno fruta y café.' },
  { word: 'nunca',     level: 'A1', sk: 'nikdy',             definition: 'Never.',                         example: 'Nunca llego tarde al trabajo.' },
  { word: 'mucho',     level: 'A1', sk: 'veľa / veľmi',      definition: 'A lot; much.',                   example: 'Tengo mucho que hacer este fin de semana.' },
  { word: 'poco',      level: 'A1', sk: 'málo',              definition: 'A little; few.',                 example: 'Hablo un poco de francés también.' },
  { word: 'bueno',     level: 'A1', sk: 'dobrý',             definition: 'Good.',                          example: '¡Qué buena idea! Vamos al parque.' },
  { word: 'malo',      level: 'A1', sk: 'zlý',               definition: 'Bad.',                           example: 'Hoy hace muy mal tiempo — llueve mucho.' },
  { word: 'grande',    level: 'A1', sk: 'veľký',             definition: 'Big; large.',                    example: 'Tienen una casa muy grande con jardín.' },
  { word: 'pequeño',   level: 'A1', sk: 'malý',              definition: 'Small; little.',                 example: 'Vivo en un apartamento pequeño pero acogedor.' },
  { word: 'encontrar', level: 'A2', sk: 'nájsť / stretnúť',  definition: 'To find or meet.',               example: 'No puedo encontrar mis llaves, ¿las has visto?' },
  { word: 'pensar',    level: 'A2', sk: 'myslieť',           definition: 'To think.',                      example: 'Pienso que deberíamos salir más temprano.' },
  { word: 'necesitar', level: 'A2', sk: 'potrebovať',        definition: 'To need.',                       example: 'Necesito comprar más café — ya no queda.' },
  { word: 'buscar',    level: 'A2', sk: 'hľadať',            definition: 'To look for; to search.',        example: 'Estoy buscando un apartamento más grande.' },
  { word: 'llegar',    level: 'A2', sk: 'prísť',             definition: 'To arrive.',                     example: '¿A qué hora llegas a casa del trabajo?' },
  { word: 'volver',    level: 'A2', sk: 'vrátiť sa',         definition: 'To return; come back.',          example: 'Volvemos a casa a las ocho de la noche.' },
  { word: 'empezar',   level: 'A2', sk: 'začať',             definition: 'To start; to begin.',            example: 'La clase empieza a las nueve en punto.' },
  { word: 'esperar',   level: 'A2', sk: 'čakať / dúfať',     definition: 'To wait; to hope.',              example: 'Espera aquí un momento — vuelvo enseguida.' },
  { word: 'llevar',    level: 'A2', sk: 'niesť / nosiť',     definition: 'To carry; to wear.',             example: '¿Qué ropa llevas cuando hace frío?' },
  { word: 'recordar',  level: 'A2', sk: 'pamätať si',        definition: 'To remember.',                   example: 'No recuerdo dónde puse las llaves esta mañana.' },
  { word: 'cambiar',   level: 'A2', sk: 'zmeniť',            definition: 'To change.',                     example: 'He cambiado de trabajo y me siento mejor.' },
  { word: 'abrir',     level: 'A2', sk: 'otvoriť',           definition: 'To open.',                       example: '¿Puedes abrir la ventana? Hace calor.' },
  { word: 'perder',    level: 'A2', sk: 'stratiť',           definition: 'To lose; to miss.',              example: 'Perdí el autobús y tuve que esperar media hora.' },
  { word: 'ayudar',    level: 'A2', sk: 'pomôcť',            definition: 'To help.',                       example: '¿Puedes ayudarme a mover esta mesa?' },
  { word: 'preguntar', level: 'A2', sk: 'opýtať sa',         definition: 'To ask a question.',             example: 'Voy a preguntar al camarero qué recomienda.' },
  { word: 'contestar', level: 'A2', sk: 'odpovedať',         definition: 'To answer; to reply.',           example: 'No contesté al teléfono — estaba en una reunión.' },
  { word: 'limpiar',   level: 'A2', sk: 'upratať',           definition: 'To clean.',                      example: 'Los sábados limpio toda la casa por la mañana.' },
  { word: 'cocinar',   level: 'A2', sk: 'variť',             definition: 'To cook.',                       example: 'Me encanta cocinar platos de diferentes países.' },
  { word: 'comprar',   level: 'A2', sk: 'kúpiť',             definition: 'To buy.',                        example: 'Voy a comprar fruta y verduras para la semana.' },
  { word: 'viajar',    level: 'A2', sk: 'cestovať',          definition: 'To travel.',                     example: 'Me encanta viajar y conocer nuevas culturas.' },
]

export function getWordOfDay() {
  const idx = Math.floor(Date.now() / 86400000) % WORDS_OF_DAY.length
  return WORDS_OF_DAY[idx]
}